### PR TITLE
feat: move to brachyura, update to 1.19.4

### PR DESCRIPTION
**Pull request by RoootTheFox**
This PR moves FoxClient away from gradle and uses brachyura as build system instead.

It also updates the target Minecraft version to 1.19.4

### CODE REVIEW

**Comment by RoootTheFox** [comment]
now builds with dependencies and runs - gonna look for bugs and eventually merge

**Comment by RoootTheFox** [comment]
shhh github don't tell anyone that i forgot to commit a few changes

**Review by PassiHD2004 — APPROVED** [review]
Looks good ig

**Comment by PassiHD2004** [comment]
> Looks good ig

Begone gradle

**Review by Flustix — APPROVED** [review]
Seems fine to me

**Comment by RoootTheFox** [comment]
manually remerging this in a new pr so i can squash merge

**Pull request merged**
