### PR TITLE
Add Biome Display 

### PR DESCRIPTION
**Pull request by PassiHD2004**
(Definetely didnt take me 4 months) and definetely didnt break and kill my mental health with the "recent" 1.19.3 commit :)

### CODE REVIEW

**Comment by RoootTheFox** [comment]
Does this include code made to work on 1.19.3? If yes, I'd prefer to wait to finish updating to 1.19.3 first and fixing the issues that come with it.

**Comment by PassiHD2004** [comment]
I mean i made it work on 1.19.3 and havent noticed any issues as of now, but yeah, idk

**Comment by PassiHD2004** [comment]
ok nvm. having some issues with foxclient rn :) crashes woo

**Comment by PassiHD2004** [comment]
so foxclient will not work with smooth boot, at least it doesnt for me rn, and many mods broke bc of 1.19.3

**Comment by PassiHD2004** [comment]
closing this

**Pull request closed without merging**
