### PR TITLE
(wip) update to 1.20

### PR DESCRIPTION
**Pull request by RoootTheFox**
# DO NOT MERGE!!
wip update to 1.20.1

### CODE REVIEW

**Comment by PassiHD2004** [comment]
should change name and desc. to 1.20.1

**Comment by PassiHD2004** [comment]
woooo, backport more stuff

**Comment by PassiHD2004** [comment]
image

maybe dont show block hud in spectator (like a toggle in settings or something)

**Comment by RoootTheFox** [comment]
~~cope :3~~

(jokes aside i might do that)

**Comment by RoootTheFox** [comment]
@PassiHD2004 @flustix @Starlight5ky are there any known issues with this? if not I'd like to merge this.

**Comment by PassiHD2004** [comment]
> @PassiHD2004 @flustix @Starlight5ky are there any known issues with this? if not I'd like to merge this.

no, except the block hud showing in spectator, but nothing gamebreaking

**Comment by RoootTheFox** [comment]
it's been a while, i think its about time to merge this lmao. (even though some things are still a bit broken)

**Pull request merged**
